create table if not exists public.pedidos_catalogo (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  cliente text not null,
  telefone text not null,
  total numeric(12,2) not null default 0,
  status text not null default 'Pendente' check (status in ('Pendente','Confirmado','Em produção','Pronto','Entregue','Cancelado')),
  origem text not null default 'catalogo',
  data timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  whatsapp_enviado boolean not null default false
);

create table if not exists public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos_catalogo(id) on delete cascade,
  produto_id bigint references public.produtos(id) on delete set null,
  nome_produto text not null,
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(12,2) not null default 0,
  subtotal numeric(12,2) not null default 0
);

alter table public.encomendas add column if not exists pedido_catalogo_id bigint references public.pedidos_catalogo(id) on delete set null;

create index if not exists pedidos_catalogo_usuario_data_idx on public.pedidos_catalogo(usuario_id, data desc);
create index if not exists pedidos_catalogo_usuario_status_idx on public.pedidos_catalogo(usuario_id, status);
create index if not exists pedido_itens_pedido_idx on public.pedido_itens(pedido_id);
create index if not exists pedido_itens_produto_idx on public.pedido_itens(produto_id);
create unique index if not exists encomendas_pedido_catalogo_uidx on public.encomendas(pedido_catalogo_id) where pedido_catalogo_id is not null;

alter table public.pedidos_catalogo enable row level security;
alter table public.pedido_itens enable row level security;

drop policy if exists "pedidos_catalogo: dono" on public.pedidos_catalogo;
create policy "pedidos_catalogo: dono" on public.pedidos_catalogo for all to authenticated
using ((select auth.uid()) = usuario_id) with check ((select auth.uid()) = usuario_id);

drop policy if exists "pedido_itens: dono" on public.pedido_itens;
create policy "pedido_itens: dono" on public.pedido_itens for all to authenticated
using (exists (select 1 from public.pedidos_catalogo p where p.id = pedido_itens.pedido_id and p.usuario_id = (select auth.uid())))
with check (exists (select 1 from public.pedidos_catalogo p where p.id = pedido_itens.pedido_id and p.usuario_id = (select auth.uid())));

revoke all on table public.pedidos_catalogo from anon;
revoke all on table public.pedido_itens from anon;
grant select, insert, update, delete on table public.pedidos_catalogo to authenticated;
grant select, insert, update, delete on table public.pedido_itens to authenticated;
grant usage, select on sequence public.pedidos_catalogo_id_seq to authenticated;
grant usage, select on sequence public.pedido_itens_id_seq to authenticated;

create or replace function public.finalizar_pedido_catalogo(p_slug text, p_cliente text, p_telefone text, p_itens jsonb)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_loja public.usuarios%rowtype;
  v_produto public.produtos%rowtype;
  v_item record;
  v_pedido_id bigint;
  v_encomenda_id bigint;
  v_total numeric(12,2) := 0;
  v_itens_confirmados pg_catalog.jsonb := '[]'::pg_catalog.jsonb;
  v_produtos_resumo text := '';
begin
  if pg_catalog.btrim(coalesce(p_cliente,'')) = '' then raise exception 'Informe seu nome.'; end if;
  if pg_catalog.length(pg_catalog.btrim(p_cliente)) > 120 then raise exception 'O nome é muito longo.'; end if;
  if pg_catalog.btrim(coalesce(p_telefone,'')) = '' then raise exception 'Informe seu telefone.'; end if;
  if pg_catalog.length(pg_catalog.btrim(p_telefone)) > 30 then raise exception 'O telefone é muito longo.'; end if;
  if pg_catalog.jsonb_typeof(p_itens) <> 'array' or pg_catalog.jsonb_array_length(p_itens) = 0 then raise exception 'O carrinho está vazio.'; end if;

  select * into v_loja from public.usuarios where slug = pg_catalog.btrim(p_slug) limit 1;
  if not found then raise exception 'Loja não encontrada.'; end if;

  insert into public.pedidos_catalogo(usuario_id,cliente,telefone)
  values(v_loja.id,pg_catalog.btrim(p_cliente),pg_catalog.btrim(p_telefone))
  returning id into v_pedido_id;

  for v_item in
    select x.id, sum(x.quantidade)::integer as quantidade
    from pg_catalog.jsonb_to_recordset(p_itens) as x(id bigint, quantidade integer)
    group by x.id order by x.id
  loop
    if v_item.id is null or v_item.quantidade is null or v_item.quantidade < 1 or v_item.quantidade > 1000 then
      raise exception 'Quantidade inválida para um produto.';
    end if;

    select * into v_produto
    from public.produtos
    where id = v_item.id and usuario_id = v_loja.id and mostrar_catalogo = true
    for update;

    if not found then raise exception 'Um produto não está mais disponível.'; end if;

    if coalesce(v_produto.quantidade,0) < v_item.quantidade then
      raise exception 'Estoque insuficiente para: % (disponível: %).',v_produto.nome,v_produto.quantidade;
    end if;

    update public.produtos
    set quantidade = quantidade - v_item.quantidade
    where id = v_produto.id;

    insert into public.pedido_itens(pedido_id,produto_id,nome_produto,quantidade,preco_unitario,subtotal)
    values(v_pedido_id,v_produto.id,v_produto.nome,v_item.quantidade,coalesce(v_produto.preco,0),coalesce(v_produto.preco,0)*v_item.quantidade);

    v_total := v_total + coalesce(v_produto.preco,0)*v_item.quantidade;

    v_produtos_resumo := case
      when v_produtos_resumo='' then v_produto.nome||' x'||v_item.quantidade
      else v_produtos_resumo||', '||v_produto.nome||' x'||v_item.quantidade
    end;

    v_itens_confirmados := v_itens_confirmados || pg_catalog.jsonb_build_object(
      'id',v_produto.id,'nome',v_produto.nome,'quantidade',v_item.quantidade,
      'preco_unitario',coalesce(v_produto.preco,0),
      'valor',coalesce(v_produto.preco,0)*v_item.quantidade
    );
  end loop;

  update public.pedidos_catalogo set total=v_total, atualizado_em=pg_catalog.now() where id=v_pedido_id;

  insert into public.encomendas(cliente,telefone,produto,valor,sinal,status,observacoes,user_id,pedido_catalogo_id)
  values(
    pg_catalog.btrim(p_cliente),pg_catalog.btrim(p_telefone),v_produtos_resumo,
    v_total,0,'Pendente','Pedido recebido pelo catálogo público. Pedido #'||v_pedido_id,
    v_loja.id,v_pedido_id
  )
  returning id into v_encomenda_id;

  return pg_catalog.jsonb_build_object(
    'sucesso',true,'pedido_id',v_pedido_id,'encomenda_id',v_encomenda_id,
    'total',v_total,'itens',v_itens_confirmados,'whatsapp',coalesce(v_loja.whatsapp,'')
  );
end;
$$;

revoke execute on function public.finalizar_pedido_catalogo(text,text,text,jsonb) from public;
grant execute on function public.finalizar_pedido_catalogo(text,text,text,jsonb) to anon, authenticated;

create or replace function public.cancelar_pedido_catalogo(p_pedido_id bigint)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare v_pedido public.pedidos_catalogo%rowtype; v_item record;
begin
  if (select auth.uid()) is null then raise exception 'Sessão necessária.'; end if;

  select * into v_pedido from public.pedidos_catalogo
  where id=p_pedido_id and usuario_id=(select auth.uid()) for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_pedido.status='Cancelado' then return pg_catalog.jsonb_build_object('sucesso',true,'ja_cancelado',true,'pedido_id',v_pedido.id); end if;
  if v_pedido.status in ('Entregue','Pronto') then raise exception 'Não é possível cancelar um pedido já finalizado.'; end if;

  for v_item in select produto_id,quantidade from public.pedido_itens where pedido_id=v_pedido.id and produto_id is not null loop
    update public.produtos set quantidade=coalesce(quantidade,0)+v_item.quantidade where id=v_item.produto_id and usuario_id=v_pedido.usuario_id;
  end loop;

  update public.pedidos_catalogo set status='Cancelado',atualizado_em=pg_catalog.now() where id=v_pedido.id;
  update public.encomendas set status='Cancelado',atualizado_em=pg_catalog.now() where pedido_catalogo_id=v_pedido.id and user_id=v_pedido.usuario_id;

  return pg_catalog.jsonb_build_object('sucesso',true,'pedido_id',v_pedido.id);
end;
$$;

revoke execute on function public.cancelar_pedido_catalogo(bigint) from public, anon;
grant execute on function public.cancelar_pedido_catalogo(bigint) to authenticated;
