-- Kroche Manager: categorias de produtos
-- Corresponde à migration aplicada no Supabase em 20260923181007.
-- Mantém produtos.categoria por compatibilidade e adiciona categoria_id.

create table if not exists public.categorias_produtos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  nome text not null,
  slug text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint categorias_produtos_usuario_nome_key unique (usuario_id, nome),
  constraint categorias_produtos_usuario_slug_key unique (usuario_id, slug)
);

alter table public.produtos add column if not exists categoria_id bigint;

alter table public.produtos
  add constraint produtos_categoria_id_fkey
  foreign key (categoria_id)
  references public.categorias_produtos(id)
  on delete set null;

insert into public.categorias_produtos (usuario_id, nome, slug)
select distinct p.usuario_id, trim(p.categoria),
  lower(regexp_replace(translate(trim(p.categoria),
  'áàãâäéèêëíìîïóòõôöúùûüç','aaaaaeeeeiiiiooooouuuuc'),
  '[^a-z0-9]+','-','g'))
from public.produtos p
where p.categoria is not null and trim(p.categoria) <> ''
on conflict (usuario_id, nome) do nothing;

update public.produtos p
set categoria_id=c.id
from public.categorias_produtos c
where c.usuario_id=p.usuario_id
  and lower(trim(c.nome))=lower(trim(p.categoria))
  and p.categoria_id is null;

create index if not exists idx_categorias_produtos_usuario on public.categorias_produtos(usuario_id);
create index if not exists idx_produtos_categoria_id on public.produtos(categoria_id);

alter table public.categorias_produtos enable row level security;
create policy "categorias_produtos: dono crud"
on public.categorias_produtos for all to authenticated
using ((select auth.uid())=usuario_id)
with check ((select auth.uid())=usuario_id);

grant select, insert, update, delete on public.categorias_produtos to authenticated;
grant usage, select on sequence public.categorias_produtos_id_seq to authenticated;
